LearningSoftware/blueprint/src/controllers/authors.py
from flask import Blueprint, render_template


authors_ctrl = Blueprint("authors", __name__)

@authors_ctrl.route("/")
def list():
    return render_template("authors/list.html")


@authors_ctrl.route("/<int:id>")
def getItem(id:int):
    return render_template("authors/detail.html", id=id)

LearningSoftware/blueprint/src/controllers/books.py
from flask import Blueprint, render_template


books_ctrl = Blueprint("books", __name__)

@books_ctrl.route("/")
def list():
    return render_template("books/list.html")


@books_ctrl.route("/<int:id>")
def getItem(id:int):
    return render_template("books/detail.html", id=id)

LearningSoftware/blueprint/templates/authors/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Details of author with id: {{id}}</h1>
    <a href=" {{ url_for('.list') }}">Go Back to List</a>
</body>
</html>

LearningSoftware/blueprint/templates/authors/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>List of authors</h1>
    
    <ul>
        <li>
            <a href="{{ url_for('.getItem', id=1) }}">Author 1</a>
        </li>
        <li>
            <a href="{{ url_for('.getItem', id=2) }}">Author 2</a>
        </li>
    </ul>

    <a href=" {{ url_for('index') }}">Go Back Home</a>

</body>
</html>

LearningSoftware/blueprint/templates/books/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Details of book with id: {{id}}</h1>
    <a href=" {{ url_for('.list') }}">Go Back to List</a>
</body>
</html>

LearningSoftware/blueprint/templates/books/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>List of books</h1>
    <ul>
        <li>
            <a href="{{ url_for('.getItem', id=1) }}">Book 1</a>
        </li>
        <li>
            <a href="{{ url_for('.getItem', id=2) }}">Book 2</a>
        </li>
    </ul>
    <a href="{{ url_for('index') }}">Go Back Home</a>
</body>
</html>

LearningSoftware/blueprint/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Blueprint</h1>

    <a href=" {{ url_for('books.list') }}">Books</a>
    <a href=" {{ url_for('authors.list') }}">Authors</a>
</body>
</html>